#! /usr/bin/env python3
# Using /home/teuben/LMT/lmtoy/data_lmt/unity/data_lmt.log
# 2021-S1-US-17 - Science
#   script generated by source_obsnum.sh
import os
import sys

from lmtoy import runs

project="2021-S1-US-17"

# Dictionary of sources, each with a list of obsnum's in this project
# negative obsnums are ignored in the combinations. See also comments.txt
# for obsnum specific comments and parameters!
on = {}

on["J1557+1540"] = \
 [ 100096, 100097, 100098, 100100, 100101, 100102,]

# parameters for the first pass of the pipeline (restart=1 is automatically enforced here)
pars1 = {}

pars1["J1557+1540"] = ""

# parameters for the (optional) second pass of the pipeline (e.g. for bank=0)
pars2 = {}

pars2["J1557+1540"] = ""

# parameters for the (optional) third pass of the pipeline (usually for bank=1)
pars3 = {}

pars3["J1557+1540"] = ""

# Found 1 source(s) for 2021-S1-US-17

if __name__ == "__main__":
    runs.mk_runs(project, on, pars1, pars2, pars3, sys.argv)
